### ISSUE TITLE
Feature request: specify the xhtml namespace if hreflang is used

### ISSUE THREAD

**Issue by davidesigner** [pgilad/gulp-sitemap#13]
Hey, thanks for your module. 

I would like to suggest you to add the famous `xmlns:xhtml="http://www.w3.org/1999/xhtml"` at the end of the `<urlset>` like that: `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">` if the function hreflang is used.

I did not find a way to do that in your module...

**Comment by pgilad** [comment]
Good idea! a PR is welcome!

**Comment by Frank3K** [comment]
@pgilad: in the code there's a [TODO in line 9](https://github.com/pgilad/gulp-sitemap/blob/3127a90ce9d9c283465305b1eb9255fcff7b7829/lib/sitemap.js#L9):

``` js
//TODO: export this to an external module
```

What was your idea here?

**Comment by pgilad** [comment]
All the sitemap generation needs to be a separate module all together, and `gulp-sitemap` needs to just use the module's functions in order to generate the sitemap from the files in streams (and supplied config).

I've done something similar with [gulp-todo](https://github.com/pgilad/gulp-todo) and [leasot](https://github.com/pgilad/leasot) where `gulp-todo` used to contain all logic, and then I extracted it to `leasot`. That way people can use the library for other build tools and possibly for cli usage.
